version: "1.1"

versioning:
  update-major: [breaking]
  update-minor: [feat, perf]
  update-patch: [build, ci, chore, fix, perf, refactor, test, docs]
  ignore-unknown: false

tag:
  pattern: "v%d.%d.%d"
  filter: ""

release-notes:
  sections:
    - name: Breaking Changes
      section-type: breaking-changes
    - name: Features
      section-type: commits
      commit-types: [feat, perf]
    - name: Bug Fixes
      section-type: commits
      commit-types: [fix]
    - name: Maintenance
      section-type: commits
      commit-types: [chore, refactor]
    - name: Documentation
      commit-types: [docs]
      section-type: commits
    - name: CI
      commit-types: [ci]
      section-type: commits

branches:
  prefix: ([a-z]+\/)?
  suffix: (-.+)?
  disable-issue: false
  skip: []
  skip-detached: false

commit-message:
  types: [build, ci, chore, docs, feat, fix, perf, refactor, revert, style, test]
  header-selector: ""
  scope:
    values: []
  footer:
    issue:
      key: jira
      key-synonyms: [Jira, JIRA]
      use-hash: false
      add-value-prefix: ""
  issue:
    regex: "[A-Z]+-[0-9]+"
