export interface NavItem {
  /**
   * The visible label for this item in the navigation. It could be a string or
   * a record of strings with the language code as the key.
   */
  label: string | Record<string, string>;
  /**
   * The link to this item's content. It could be a string or a record of
   * strings with the language code as the key.
   */
  href: string | Record<string, string>;
}

export interface MultiSidebarOptions {
  /**
   * How the sidebar switcher is rendered.
   *
   * - `horizontalList`: one tab per sidebar above the sidebar entries.
   * - `dropdown`: a compact select listing every sidebar.
   * - `hidden`: no switcher, only the sidebar containing the current page is rendered.
   *
   * @default "horizontalList"
   */
  switcherStyle?: "horizontalList" | "dropdown" | "hidden";
}

export interface ThemeCelestiaOptions {
  nav?: NavItem[];

  /**
   * Turn every top-level entry of the Starlight `sidebar` config into its own sidebar, with a
   * switcher to move between them.
   *
   * Every top-level entry must be a group or autogenerated when this is set.
   *
   * @default undefined
   */
  multiSidebar?: MultiSidebarOptions;

  /**
   * `starlight-theme-celestia` supports two styling systems: pure CSS and Tailwind
   * CSS.
   *
   * By default, `starlight-theme-celestia` will detect if Tailwind CSS is passed to
   * the Astro config, and use Tailwind CSS if it is. You can also force the
   * theme to use a specific styling system by setting the `stylingSystem`
   * option to `css` or `tailwind`.
   *
   * @default "detect"
   */
  stylingSystem?: "css" | "tailwind" | "detect";
}

/**
 * @internal
 */
export interface ConfigSerialized {
  nav?: NavItem[];
  multiSidebar?: MultiSidebarOptions;
  rootHref: string;
}
